---
- hosts: all
  become: true
  tasks:
  - name: Install Apache HttpServer
    yum:
     name: httpd
     state: present
  - name: Start the Apache HttpServer
    service:
     name: httpd
     state: started
  - name: Copy index.html
    copy:
     src: index.html
     dest: /var/www/html/index.html    
...